### ISSUE TITLE
constants.py should not invoke schemaview

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom-py#322]
This is called *when importing sssom-py:

https://github.com/mapping-commons/sssom-py/blob/5490672f3bb8853f0a9a6d01a223a7f476a37f1a/sssom/constants.py#L12-L17

in general it's not a good idea to have logic executed when a package is imported. logic should only be done on specific invocation of that logic.

in this case it's particularly problematic as this invokes a network call...

**Comment by matentzn** [comment]
@hrshdhgd - can you remind me why a "network call" is required here?

**Comment by hrshdhgd** [comment]
I'm guessing the network call has to d with `pkg_resources` that calls the schema from `sssom_schema`. I do not fully understand this request. I was going to ask @cmungall for some clarification during our one-on-one but since you're not clear about it either, Chris could you please enlighten us both?
