### ISSUE TITLE
SSSOM code broken

### ISSUE THREAD

**Issue by cthoyt** [mapping-commons/sssom-py#340]
It's really frustrating to rely on this package. Sometimes it just breaks and then my builds that are relying on it don't work. This makes me want to make my own SSSOM package, which I won't have time to maintain either, but at least I will be able to know how it works...

Can someone help figure out what's going on in https://github.com/biopragmatics/biomappings/actions/runs/4075209444/jobs/7021308103?

**Comment by matentzn** [comment]
I think (not sure) this is not a sssom-py problem. Perhaps we need to start fixing linkml dependencies, this is happening to me also from time to time. How did we address this last time @hrshdhgd? I this because of a recent breaking change in Linkml?

I am not sure how to guard against these issues. Maybe we need weekly updates of the poetry lockfile running all the tests to ensure that sssom py still works with its dependencies?

**Comment by cthoyt** [comment]
No this is just code that assumes something is an instance of a class, and it's actually a class itself - code completely in this package

https://github.com/mapping-commons/sssom-py/blob/c490d6740dab1f6c9213984bfae98d7306238c0f/sssom/parsers.py#L312-L314

**Comment by matentzn** [comment]
Its a recent change, but I am really surprised the QC checks didn't catch this case!
