### ISSUE TITLE
Docs: Are built-in prefixes in metadata required, or recommended?

### ISSUE THREAD

**Issue by joeflack4** [mapping-commons/sssom-py#535]
## Overview
Just a request to have documentation on this.

## Context
This is coming from #513, where I was creating a `MappingSetDataFrame` with no pre-initialized `Converter`. The `metadata` created included some built-in prefixes which do not appear anywhere in my mapping set.

## Thoughts
I prefer to be minimalist to the point that I want prefixes in my metadata if and only if they appear in mapping set / any of the rows in my TSV. But I do see the UX benefits of including common built-ins.

**Comment by matentzn** [comment]
Sorry I accidentally moved the issue here as it was talking about implementation details, but the issue title is indeed about the model, and not the toolkit. Can you create new issue in sssom linking to this one here w/o mentioning implementation details? Just ask for a clarification in the docs on whether built-in prefixes are optional or not in the metadata. Sorry about that - my mistake.

**Comment by joeflack4** [comment]
Done!
- https://github.com/mapping-commons/sssom/issues/365

**Comment by joeflack4** [comment]
https://github.com/mapping-commons/sssom/issues/365 is closed now, and I don't see a reason for this one to still be open; closing.
